### ISSUE TITLE
Trouble with rgba as default of mixin parameter

### ISSUE THREAD

**Issue by gregorko** [tomyeh/ZUSS#10]
Hi...

I'm having troubles with the following rule:

@box-shadow(@shadow: 0 1px 3px rgba(0,0,0,.25)) {
  -webkit-box-shadow: @shadow;
     -moz-box-shadow: @shadow;
          box-shadow: @shadow;
}

Am I doing something wrong or is it a bug in the parser?

Thanks,
Gregor

**Comment by tomyeh** [comment]
'(' and ',' have special meaning after ':'. They are considered as special symbols of an expression.
The solution is to escape it with a quote such as:

``` css
@box-shadow(@shadow: '0 1px 3px rgba(0,0,0,.25)') {
    -webkit-box-shadow: @shadow;
    -moz-box-shadow: @shadow;
    box-shadow: @shadow;
}
```
