### ISSUE TITLE
Method for String interpolation

### ISSUE THREAD

**Issue by jlangston** [tomyeh/ZUSS#12]
With Less embedding a variable in a string is pretty easy with the @{token} syntax. Is there already a similar method to do this in zuss?

Less Example 

``` css
@base-url: "http://assets.fnord.com";
background-image: url("@{base-url}/images/bg.png");
```

**Comment by jlangston** [comment]
I figured out a way to do this using the java method call feature

``` java
  public static String getCssBaseImgUri(String img)
  {
    return "'" + cssBaseImgUri + img + "'";
  }
```

cssBaseImgUri is a Static string which is the base image path for all the css images

``` css
@setImgPath(@imgName): @import packagepath.Class#getCssBaseImgUri;

body {
  background-image: url(@setImgPath(BodyBg.gif));
}
```
