### ISSUE TITLE
Issues with negative Numbers and Sizes

### ISSUE THREAD

**Issue by laeubi** [tomyeh/ZUSS#25]
I'm facing several issues with negative numbers, eg 
top: -@VARIABLE
 outputes
top: - 2.5mm;
(there is a space betwenn the minus sign an the value)

Using
top: @eval(-1*@VARIABLE)
 outputs
top: 2.5mm

Using
top: @eval(-@VARIABLE)
 outputs
org.zkoss.zuss.ZussException: Unable to negate a size, 2.5mm

From the source I can't see why it should not be possible to negate a size (since it's an ordinary number with a unit), so thin can be added. Another strange thing is that the negate operator only negates sizes and colors but not Numbers.

**Comment by laeubi** [comment]
Testcase

``` css
@VARIABLE: 2.5mm;

div1 {
    top: -@VARIABLE;
}
div2 {
    top: @eval(-1*@VARIABLE);
}
div 3 {
    top: @eval(-@VARIABLE);
}
```
